name: cleanBib
channels:
  - conda-forge
dependencies:
  - python
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pybtex
    - glob
    - csv
    - numpy
    - bibtexparser
    - subprocess
    - os
    - pandas
    - re
    - pylatexenc
    - sos
    - sos-notebook
    - habanero
    - tqdm
    - json
    - pickle
    - urllib
    - ethnicolr
    - matplotlib
    - seaborn